Implement 50 move draw
ashelkovnykov/urbit-chess pull request #90
Opened 2022-12-04 22:56 UTC by rovmug-ticfyn

2022-12-05 03:10 UTC, ashelkovnykov requested changes
Minor, but on lines 529 and 533 in `%chess-debug-inject`, the initial state of `special-draws-available` depends on the FEN being injected (namely on whether the `ply-50-move-rule` is above 100, since it's impossible for an injected position to be a repetition).

2022-12-06 17:13 UTC, ashelkovnykov requested changes
Bugs

2022-12-06 17:13 UTC, ashelkovnykov commented on src/urbit/app/chess.hoon
> +                  %chess-update  !>([%position game-id.action fen (gth ply-50-move-rule.u.new-position 100)])
Should be `gte`, not `gth`

2022-12-06 17:13 UTC, ashelkovnykov commented on src/urbit/app/chess.hoon
> +        games  (~(put by games) game-id.action [game.action u.new-position *(map @t @ud) (gth ply-50-move-rule.u.new-position 100) & | | |])
Same as above

2022-12-06 17:13 UTC, ashelkovnykov commented on src/urbit/app/chess.hoon
> +            (check-50-move-rule u.new-position)
Syntax error. Should be:
```
?|  (check-threefold new-fen-repetition u.new-position)
    (check-50-move-rule u.new-position)
==
```

2022-12-08 22:29 UTC, ashelkovnykov approved these changes
LGTM. Code already correct, but duplicates logic (see comments below). Can be merged after resolution.

2022-12-08 22:29 UTC, ashelkovnykov commented on src/urbit/app/chess.hoon
> +                  %chess-update  !>([%position game-id.action fen (gte ply-50-move-rule.u.new-position 100)])
I just realized we're replicating the `check-50-move-rule` logic - we should be calling `check-50-move-rule` instead:
```
:-  :~  :*  %give  %fact  ~[/game/(scot %da game-id.action)/updates]
            %chess-update  !>([%position game-id.action fen (check-50-move-rule u.new-position)])
```

2022-12-08 22:29 UTC, ashelkovnykov commented on src/urbit/app/chess.hoon
> +        games  (~(put by games) game-id.action [game.action u.new-position *(map @t @ud) (gte ply-50-move-rule.u.new-position 100) & | | |])
Same as above:
```
games (~(put by games) game-id.action [game.action u.new-position *(map @t @ud) (check-50-move-rule u.new-position) & | | |])
```

2022-12-08 22:29 UTC, ashelkovnykov requested changes
Oh, and squash to one commit please

2022-12-09 02:02 UTC, rovmug-ticfyn commented
Ready to merge now

2022-12-10 20:28 UTC, ashelkovnykov approved these changes
LGTM

2022-12-10 20:28 UTC, merged