Friends frontend
ashelkovnykov/urbit-chess pull request #93
Opened 2022-12-07 22:41 UTC by bonbud-macryg

This PR is functional but the UI has some rough edges, I'd like to hold off on polishing that up until this code is merged with the outgoing challenges list in #7, so I can get the whole Challenges menu working as intended.

2022-12-08 23:17 UTC, ashelkovnykov requested changes
I'm not even going to test the interface myself, that's how much I trust you (totally not because I'm too lazy to spin up two moons and install `%chess` + `%pals` on both of them - how could you even think that)

2022-12-08 23:17 UTC, ashelkovnykov commented on src/frontend/tsx/Challenges.tsx
> +  }
This function should go in `ts/helpers/urbitChess` - that's the default place for pokes/scries

2022-12-08 23:17 UTC, ashelkovnykov commented on src/frontend/tsx/Challenges.tsx
> +  }
Would it be difficult to instead have the quick challenge button open the same pop-up that "New Challenge" opens, but pre-populate it with the friendly ship's `@p`? Would solve the problems of only being able to challenge as random, needing a default description, and replicating success/failure logic.

2022-12-09 20:17 UTC, rovmug-ticfyn commented on src/frontend/tsx/Challenges.tsx
> +                    <button className='quick-game' onClick={() => {setWho('~' + friend); openModal() }}>Challenge</button>
Space needed after `{`
`...{ setWho('~' + friend)...`

2022-12-10 13:11 UTC, bonbud-macryg commented
I think this PR's reformatted scry in `helpers/urbitChess` establishes a pattern which #6 could follow for getting the list of completed games. @brbenji

2022-12-10 15:35 UTC, brbenji commented
> I think this PR's reformatted scry in `helpers/urbitChess` establishes a pattern which #6 could follow for getting the list of completed games. @brbenji

Cool! Soon I’ll be focusing in that direction.

2022-12-10 21:20 UTC, ashelkovnykov approved these changes
LGTM - two minor comments, crush to one commit, and then feel free to merge yourself

2022-12-10 21:20 UTC, ashelkovnykov commented on src/frontend/tsx/Challenges.tsx
> +              disabled={ challengingFriend ? true : false }/>
`challengingFriend` is already a boolean, don't need to use the ternary operator

2022-12-10 21:20 UTC, ashelkovnykov commented on src/frontend/tsx/Challenges.tsx
> +import { pokeAction, scry, challenge, acceptGame, declineGame, findFriends } from '../ts/helpers/urbitChess'
I think `scry` is unused

2022-12-10 23:18 UTC, merged